# Generated by Django 3.2.16 on 2023-06-23 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Амплуа',
                'verbose_name_plural': 'Амплуа',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Имя')),
                ('surname', models.TextField(max_length=255, verbose_name='Фамилия')),
                ('number', models.IntegerField(verbose_name='Номер игрока')),
                ('photo', models.ImageField(upload_to='photos/players/%Y/%m/%d', verbose_name='Фото')),
                ('date_birthday', models.DateField()),
                ('country', models.TextField()),
                ('height', models.IntegerField(verbose_name='Рост')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Вес')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('grip', models.TextField(choices=[('Левый', 'Левый'), ('Правый', 'Правый')], default='Левый', verbose_name='Хват')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='players.category', verbose_name='Амплуа')),
            ],
            options={
                'verbose_name': 'Игрока',
                'verbose_name_plural': 'Игроки',
                'ordering': ['-time_create', 'name'],
            },
        ),
    ]
