# Generated by Django 3.2.16 on 2023-06-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='content',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='players',
            name='country',
            field=models.TextField(verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='players',
            name='date_birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
