# Generated by Django 3.2.16 on 2023-06-23 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20230623_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='date_birthday',
        ),
    ]
